### ISSUE TITLE
Úkol 1 hotový

### ISSUE THREAD

**Issue by MarcelaHR** [MarcelaHR/python-042023#1]
@pesikj Ahoj Jirko, pokusila jsem se odevzdat první úkol, ale nešlo mi synchronizovat z visual studio, tak jsem nahrála přímo. Mohli bychom se pak podívat třeba o přestávce ve čtvrtek na ta chybová hlášení, co mi to dává? Předem moc díky. m

**Comment by pesikj** [comment]
Ahoj Marcelo, určitě se na to podíváme. Mrknu na to zítra a pokud bude něco jednoduchého na opravu, tak ti to rovnou vložím sem, ostatní věci můžeme probrat ve čtvrtek :-)

**Comment by MarcelaHR** [comment]
Ještě jsem to podle tvého nového videa předělala do Jupyter notebooku. Ale stejně jsem musela upload ručně. Sice se mi to tvářilo, že se to commituje přímo z Visual Studia, ale nevím kam - nemohla jsem ten soubor nikde na Githubu najít. :-(

**Comment by pesikj** [comment]
@MarcelaHR Řešení úkolu je úplně super :-)

Pokud by ti vadily warningy, které pandas píše, je možné je vyřešit pomocí reset_index(). Ale na výsledek to nemá vliv, je to jen warning, řešení je jinak super :-)

```py
presidents = top_two_candidates.dropna(subset=["runner_up_votes", "abs_diff"])
presidents = presidents.reset_index()
presidents["relative_margin"] = presidents["abs_diff"] / presidents["totalvotes"]
presidents.head()
```

```py
winners = candidates[candidates["rank"] == 1]
winners = winners.reset_index()
winners.head()
```

**Comment by MarcelaHR** [comment]
@pesikj Moc děkuju za pochvalu! Snažila jsem se ;-) A dost pomohly i ty nápovědy.
Taky díky za tip, jak se zbavit těch varování. Ještě jsem našla, že pomůže udělat .copy() - takhle jsem to pak použila u cvičení ze 4. lekce a taky funguje.
uchazeci_filtered = uchazeci[uchazeci["score"] > 0].copy()
uchazeci_filtered
Ještě musím vychytat, kdy to můžu napsat nakonec na řádek s kódem a kdy na nový řádek, jako máš třeba ty výše ten .reset_index(). Zatím to dělám způsobem pokus - omyl :-))
Ale s tím .reset_index() ty tabulky pak vypadají líp díky přečíslování.
Moc díky!
