### ISSUE TITLE
Úkol č. 3 hotový

### ISSUE THREAD

**Issue by MarcelaHR** [MarcelaHR/python-042023#3]
Ahoj Jirko @pesikj ,
zpracovala jsem i třetí úkol. Budu ráda za tvé připomínky.
Díky!
m

**Comment by pesikj** [comment]
Ahoj Marcelo, je to úplně super a moc se mi líbí, jak jsi nad tím přemýšlela.
Ohledně BMI - to je super úvaha. Teoreticky by to třeba mohlo být tak, že tam je parabolická vztah. Velmi malé a velmi vysoké hodnoty indexu mají negativní vliv na délku života a hodnoty uprostřed mají pozitivní.
U záškrtu to nedokážu vysvětlit. Tvá hypotéza zní velmi rozumně. Ale obecně u koeficientů, které nejsou statisticky významné, mohou vycházet divné hodnoty. Tím, že to na data nemá praktický vliv (jak jsi ukázala), tak klidně může vyjít nesmysl. :-)
